import React, { useState, useEffect, useRef } from "react";
import Navbar from "../components/common/Navbar";
import Sidebar from "../components/common/Sidebar";
import { useAuth } from "../context/AuthContext";
import { getMyMoodsApi } from "../api/moodApi";
import { 
  PieChart, Pie, Cell, 
  LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer 
} from "recharts";

import { jsPDF } from "jspdf";
import { toPng } from "html-to-image";

const CHART_COLORS = {
  joy: "#facc15", calm: "#38bdf8", stress: "#f87171", anxiety: "#fb923c",
  sadness: "#a78bfa", anger: "#f472b6", fatigue: "#94a3b8", love: "#f472b6",
  fear: "#c084fc", neutral: "#4ade80", surprise: "#2dd4bf", disgust: "#a3e635",
};

const ReportsPage = () => {
  const { user, logout, isAdmin } = useAuth();
  const [moods, setMoods] = useState([]);
  const [loading, setLoading] = useState(true);
  const [isDownloading, setIsDownloading] = useState(false);
  
  const reportRef = useRef(null);

  const [pieData, setPieData] = useState([]);
  const [trendData, setTrendData] = useState([]);
  const [avgSentiment, setAvgSentiment] = useState("Neutral");
  const [streak, setStreak] = useState(0);

  useEffect(() => {
    const fetchAnalytics = async () => {
      try {
        setLoading(true);
        const response = await getMyMoodsApi();
        const fetchedMoods = Array.isArray(response) ? response : (response.data || []);
        setMoods(fetchedMoods);

        if (fetchedMoods.length === 0) return;

        const emotionCounts = {};
        let totalSentimentScore = 0;

        fetchedMoods.forEach((m) => {
          const emotion = m.predictedEmotion?.toLowerCase() || "neutral";
          emotionCounts[emotion] = (emotionCounts[emotion] || 0) + 1;
          if (m.sentimentLabel === "positive") totalSentimentScore += 1;
          else if (m.sentimentLabel === "negative") totalSentimentScore -= 1;
        });

        setPieData(Object.keys(emotionCounts).map(key => ({
          name: key.charAt(0).toUpperCase() + key.slice(1),
          value: emotionCounts[key],
          color: CHART_COLORS[key] || "#94a3b8"
        })));

        const avg = totalSentimentScore / fetchedMoods.length;
        setAvgSentiment(avg > 0.3 ? "Positive" : avg < -0.3 ? "Negative" : "Neutral");

        const trendMap = {};
        fetchedMoods.forEach((m) => {
          const date = new Date(m.createdAt).toLocaleDateString("en-US", { month: "short", day: "numeric" });
          let score = m.sentimentLabel === "positive" ? 1 : m.sentimentLabel === "negative" ? -1 : 0;
          if (!trendMap[date]) trendMap[date] = { date, totalScore: score, count: 1 };
          else { trendMap[date].totalScore += score; trendMap[date].count += 1; }
        });

        setTrendData(Object.values(trendMap).map(item => ({
          date: item.date,
          score: Number((item.totalScore / item.count).toFixed(2))
        })).reverse());

        setStreak(Math.min(fetchedMoods.length, 7));

      } catch (err) {
        console.error("Failed to load reports:", err);
      } finally {
        setLoading(false);
      }
    };
    fetchAnalytics();
  }, []);

  // 🚨 Professional PDF Generation Logic
  const handleDownloadPDF = async () => {
    if (!reportRef.current) return;

    try {
      setIsDownloading(true);
      
      const dataUrl = await toPng(reportRef.current, {
        quality: 1.0,
        pixelRatio: 2,
        backgroundColor: '#ffffff', // Report එක සුදු පාට පසුබිමක තිබීම Professional වැඩියි
        style: { color: '#000000' } // PDF එක ඇතුළේ text කළු පාටින් තැබීම
      });
      
      const pdf = new jsPDF("p", "mm", "a4");
      const dateStr = new Date().toLocaleDateString();
      
      // Header එකක් එකතු කිරීම
      pdf.setFontSize(22);
      pdf.setTextColor(20, 184, 166); // Teal color
      pdf.text("MindTuneX Wellness Report", 15, 20);
      
      pdf.setFontSize(10);
      pdf.setTextColor(100);
      pdf.text(`User: ${user?.fullName || "Valued User"} | Date: ${dateStr}`, 15, 28);
      
      const pdfWidth = pdf.internal.pageSize.getWidth() - 30;
      const imgProps = pdf.getImageProperties(dataUrl);
      const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;

      // පින්තූරය (Charts) ඇතුළත් කිරීම
      pdf.addImage(dataUrl, "PNG", 15, 40, pdfWidth, pdfHeight);
      
      // Footer එකක් එකතු කිරීම
      pdf.setFontSize(9);
      pdf.text("Generated by MindTuneX AI - Your Emotional Companion", 105, 285, { align: "center" });
      
      pdf.save(`MindTuneX_Report_${user?.fullName?.replace(" ", "_")}.pdf`);
      
    } catch (error) {
      console.error("Error generating PDF:", error);
      alert("Failed to download PDF.");
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <div className="flex min-h-screen bg-linear-to-br from-slate-50 to-sky-50 dark:from-slate-900 dark:to-slate-800 transition-colors duration-300">
      <Sidebar />

      <div className="flex flex-1 flex-col">
        <Navbar user={user} onLogout={logout} isAdmin={isAdmin} />

        <main className="flex-1 overflow-y-auto p-6 lg:p-10">
          <div className="mx-auto max-w-5xl space-y-10">
            
            <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
              <div>
                <h1 className="font-serif text-4xl font-semibold tracking-tight text-slate-800 dark:text-white transition-colors">
                  Your <span className="text-transparent bg-clip-text bg-linear-to-r from-teal-500 to-sky-600">Analytics</span>
                </h1>
                <p className="mt-1 text-slate-500 dark:text-slate-400">Track and export your mental wellness progress.</p>
              </div>

              <button 
                onClick={handleDownloadPDF}
                disabled={isDownloading || loading || moods.length === 0}
                className="flex items-center justify-center gap-2 rounded-3xl bg-teal-600 px-6 py-3 text-sm font-bold text-white shadow-xl hover:bg-teal-700 transition-all active:scale-95 disabled:bg-slate-400"
              >
                {isDownloading ? "Preparing Document..." : "📥 Download PDF Report"}
              </button>
            </div>

            {loading ? (
              <div className="flex h-64 items-center justify-center">
                <div className="h-10 w-10 animate-spin rounded-full border-4 border-t-teal-500"></div>
              </div>
            ) : (
              <div className="space-y-10">
                {/* 🚨 PDF එකට Capture වෙන ප්‍රදේශය */}
                <div ref={reportRef} className="space-y-10 p-6 bg-white dark:bg-slate-900 rounded-3xl">
                  
                  <div className="grid grid-cols-1 gap-6 sm:grid-cols-3">
                    <StatCard label="Total Logs" val={moods.length} color="text-slate-800 dark:text-white" />
                    <StatCard label="Overall Sentiment" val={avgSentiment} color={avgSentiment === 'Positive' ? 'text-emerald-500' : 'text-rose-500'} />
                    <StatCard label="Active Streak" val={`${streak} Days`} color="text-teal-500" />
                  </div>

                  <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                    <ChartBox title="Sentiment Trend">
                      <ResponsiveContainer width="100%" height="100%">
                        <LineChart data={trendData}>
                          <CartesianGrid strokeDasharray="3 3" opacity={0.1}/>
                          <XAxis dataKey="date" fontSize={10} />
                          <YAxis domain={[-1, 1]} hide />
                          <Tooltip />
                          <Line isAnimationActive={false} type="monotone" dataKey="score" stroke="#14b8a6" strokeWidth={3} dot={{ r: 3 }} />
                        </LineChart>
                      </ResponsiveContainer>
                    </ChartBox>

                    <ChartBox title="Emotion Breakdown">
                      <ResponsiveContainer width="100%" height="100%">
                        <PieChart>
                          <Pie isAnimationActive={false} data={pieData} innerRadius={60} outerRadius={80} paddingAngle={5} dataKey="value">
                            {pieData.map((entry, index) => <Cell key={`cell-${index}`} fill={entry.color} />)}
                          </Pie>
                          <Tooltip />
                          <Legend wrapperStyle={{ fontSize: '10px' }}/>
                        </PieChart>
                      </ResponsiveContainer>
                    </ChartBox>
                  </div>
                </div>
              </div>
            )}
          </div>
        </main>
      </div>
    </div>
  );
};

// Reusable Helper Components for the Report
const StatCard = ({ label, val, color }) => (
  <div className="rounded-2xl border border-slate-100 dark:border-slate-800 p-6 bg-slate-50/50 dark:bg-slate-800/30">
    <p className="text-[10px] font-bold uppercase tracking-widest text-slate-400">{label}</p>
    <p className={`mt-2 text-3xl font-bold ${color}`}>{val}</p>
  </div>
);

const ChartBox = ({ title, children }) => (
  <div className="rounded-2xl border border-slate-100 dark:border-slate-800 p-6">
    <h3 className="text-xs font-bold uppercase tracking-widest text-slate-400 mb-6">{title}</h3>
    <div className="h-64 w-full">{children}</div>
  </div>
);

export default ReportsPage;