import jsPDF from "jspdf";

export const generateMoodReport = (insight) => {
  const doc = new jsPDF();

  // ===== HEADER =====
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("MindTuneX", 20, 20);

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("AI-Powered Mood Analysis Report", 20, 28);

  // Line
  doc.setDrawColor(200);
  doc.line(20, 32, 190, 32);

  // ===== USER SUMMARY =====
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Summary Overview", 20, 45);

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");

  doc.text(`Total Entries: ${insight?.totalEntries || 0}`, 20, 55);
  doc.text(`Average Sentiment: ${insight?.avgSentiment || "N/A"}`, 20, 65);
  doc.text(`Top Emotion: ${insight?.topEmotion || "N/A"}`, 20, 75);

  // ===== SUMMARY TEXT BOX =====
  doc.setFont("helvetica", "bold");
  doc.text("AI Insight Summary", 20, 90);

  doc.setFont("helvetica", "normal");

  doc.text(
    insight?.summaryText || "No summary available",
    20,
    100,
    { maxWidth: 170 }
  );

  // ===== EMOTION BREAKDOWN =====
  const emotionCounts = insight?.emotionCounts || {};
  const entries = Object.entries(emotionCounts);

  let startY = 130;

  if (entries.length > 0) {
    doc.setFont("helvetica", "bold");
    doc.text("Emotion Breakdown", 20, startY);

    doc.setFont("helvetica", "normal");
    startY += 10;

    entries.forEach(([emotion, value]) => {
      doc.text(`${emotion}: ${value}`, 25, startY);
      startY += 8;
    });
  }

  // ===== FOOTER =====
  doc.setFontSize(10);
  doc.setTextColor(150);
  doc.text(
    "Generated by MindTuneX • Confidential Report",
    20,
    280
  );

  // ===== SAVE =====
  doc.save("MindTuneX_Mood_Report.pdf");
};